ACTION_VIEW = "View {} {}"
ACTION_LIST = "List {} {}"
ACTION_CREATE = "Create {} {}"
ACTION_UPDATE = "Update {} {}"
ACTION_PARTIAL_UPDATE = "Partial Update {} {}"
ACTION_DESTROY = "Destroy {} {}"
ACTION_CANCEL = "Cancel {} {}"